//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Center.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="http://tempuri.org/", ItemName="long")]
    [System.SerializableAttribute()]
    public class ArrayOfLong : System.Collections.Generic.List<long> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SendSoap")]
    public interface SendSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        SMS_Center.ServiceReference1.SendSmsResponse SendSms(SMS_Center.ServiceReference1.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<SMS_Center.ServiceReference1.SendSmsResponse> SendSmsAsync(SMS_Center.ServiceReference1.SendSmsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        SMS_Center.ServiceReference1.GetCreditResponse GetCredit(SMS_Center.ServiceReference1.GetCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        System.Threading.Tasks.Task<SMS_Center.ServiceReference1.GetCreditResponse> GetCreditAsync(SMS_Center.ServiceReference1.GetCreditRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://tempuri.org/", Order=0)]
        public SMS_Center.ServiceReference1.SendSmsRequestBody Body;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(SMS_Center.ServiceReference1.SendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SMS_Center.ServiceReference1.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool isflash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string udh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public SMS_Center.ServiceReference1.ArrayOfLong recId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public byte[] status;
        
        public SendSmsRequestBody() {
        }
        
        public SendSmsRequestBody(string username, string password, SMS_Center.ServiceReference1.ArrayOfString to, string from, string text, bool isflash, string udh, SMS_Center.ServiceReference1.ArrayOfLong recId, byte[] status) {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SMS_Center.ServiceReference1.SendSmsResponseBody Body;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(SMS_Center.ServiceReference1.SendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendSmsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SMS_Center.ServiceReference1.ArrayOfLong recId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] status;
        
        public SendSmsResponseBody() {
        }
        
        public SendSmsResponseBody(int SendSmsResult, SMS_Center.ServiceReference1.ArrayOfLong recId, byte[] status) {
            this.SendSmsResult = SendSmsResult;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCredit", Namespace="http://tempuri.org/", Order=0)]
        public SMS_Center.ServiceReference1.GetCreditRequestBody Body;
        
        public GetCreditRequest() {
        }
        
        public GetCreditRequest(SMS_Center.ServiceReference1.GetCreditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCreditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetCreditRequestBody() {
        }
        
        public GetCreditRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCreditResponse", Namespace="http://tempuri.org/", Order=0)]
        public SMS_Center.ServiceReference1.GetCreditResponseBody Body;
        
        public GetCreditResponse() {
        }
        
        public GetCreditResponse(SMS_Center.ServiceReference1.GetCreditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCreditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double GetCreditResult;
        
        public GetCreditResponseBody() {
        }
        
        public GetCreditResponseBody(double GetCreditResult) {
            this.GetCreditResult = GetCreditResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSoapChannel : SMS_Center.ServiceReference1.SendSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSoapClient : System.ServiceModel.ClientBase<SMS_Center.ServiceReference1.SendSoap>, SMS_Center.ServiceReference1.SendSoap {
        
        public SendSoapClient() {
        }
        
        public SendSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS_Center.ServiceReference1.SendSmsResponse SMS_Center.ServiceReference1.SendSoap.SendSms(SMS_Center.ServiceReference1.SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public int SendSms(string username, string password, SMS_Center.ServiceReference1.ArrayOfString to, string from, string text, bool isflash, string udh, ref SMS_Center.ServiceReference1.ArrayOfLong recId, ref byte[] status) {
            SMS_Center.ServiceReference1.SendSmsRequest inValue = new SMS_Center.ServiceReference1.SendSmsRequest();
            inValue.Body = new SMS_Center.ServiceReference1.SendSmsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            inValue.Body.udh = udh;
            inValue.Body.recId = recId;
            inValue.Body.status = status;
            SMS_Center.ServiceReference1.SendSmsResponse retVal = ((SMS_Center.ServiceReference1.SendSoap)(this)).SendSms(inValue);
            recId = retVal.Body.recId;
            status = retVal.Body.status;
            return retVal.Body.SendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMS_Center.ServiceReference1.SendSmsResponse> SMS_Center.ServiceReference1.SendSoap.SendSmsAsync(SMS_Center.ServiceReference1.SendSmsRequest request) {
            return base.Channel.SendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMS_Center.ServiceReference1.SendSmsResponse> SendSmsAsync(string username, string password, SMS_Center.ServiceReference1.ArrayOfString to, string from, string text, bool isflash, string udh, SMS_Center.ServiceReference1.ArrayOfLong recId, byte[] status) {
            SMS_Center.ServiceReference1.SendSmsRequest inValue = new SMS_Center.ServiceReference1.SendSmsRequest();
            inValue.Body = new SMS_Center.ServiceReference1.SendSmsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.to = to;
            inValue.Body.from = from;
            inValue.Body.text = text;
            inValue.Body.isflash = isflash;
            inValue.Body.udh = udh;
            inValue.Body.recId = recId;
            inValue.Body.status = status;
            return ((SMS_Center.ServiceReference1.SendSoap)(this)).SendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS_Center.ServiceReference1.GetCreditResponse SMS_Center.ServiceReference1.SendSoap.GetCredit(SMS_Center.ServiceReference1.GetCreditRequest request) {
            return base.Channel.GetCredit(request);
        }
        
        public double GetCredit(string username, string password) {
            SMS_Center.ServiceReference1.GetCreditRequest inValue = new SMS_Center.ServiceReference1.GetCreditRequest();
            inValue.Body = new SMS_Center.ServiceReference1.GetCreditRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            SMS_Center.ServiceReference1.GetCreditResponse retVal = ((SMS_Center.ServiceReference1.SendSoap)(this)).GetCredit(inValue);
            return retVal.Body.GetCreditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMS_Center.ServiceReference1.GetCreditResponse> SMS_Center.ServiceReference1.SendSoap.GetCreditAsync(SMS_Center.ServiceReference1.GetCreditRequest request) {
            return base.Channel.GetCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMS_Center.ServiceReference1.GetCreditResponse> GetCreditAsync(string username, string password) {
            SMS_Center.ServiceReference1.GetCreditRequest inValue = new SMS_Center.ServiceReference1.GetCreditRequest();
            inValue.Body = new SMS_Center.ServiceReference1.GetCreditRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((SMS_Center.ServiceReference1.SendSoap)(this)).GetCreditAsync(inValue);
        }
    }
}
